# -*- coding: utf-8 -*-
"""DATABASE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNgONYBZpRuwjaa4xwrqiTSevgU0pMwj
"""

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base
from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./syngrid_chat.db")

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {}
)

SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)
Base = declarative_base()