# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNgONYBZpRuwjaa4xwrqiTSevgU0pMwj
"""

from fastapi import FastAPI, Depends, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from database import SessionLocal, Base, engine
from models import ChatHistory, UserContact
from schemas import (
    ChatQueryCreate, ChatResponse, UserContactCreate,
    UserContactResponse, ChatHistoryResponse, InitStatusResponse
)
from syngrid_ai import SyngridAI
import os
from typing import List

# Create tables
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="Syngrid AI Chatbot API",
    description="AI-powered chatbot for Syngrid Technologies",
    version="1.0.0"
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize AI
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
SYNGRID_WEBSITE = os.getenv("SYNGRID_WEBSITE", "https://syngrid.com/")
MODEL = os.getenv("MODEL", "kwaipilot/kat-coder-pro:free")

ai_assistant = SyngridAI(OPENROUTER_API_KEY, MODEL)


# Dependency
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# Initialize AI in background
@app.on_event("startup")
async def startup_event():
    def init_ai():
        ai_assistant.initialize(SYNGRID_WEBSITE, max_pages=40)

    import threading
    thread = threading.Thread(target=init_ai)
    thread.start()


# Routes
@app.get("/")
def root():
    return {"message": "Syngrid AI Chatbot API is running", "status": "active"}


@app.get("/status", response_model=InitStatusResponse)
def get_status():
    return {
        "ready": ai_assistant.status["ready"],
        "pages_scraped": ai_assistant.status["pages_scraped"],
        "message": "Ready" if ai_assistant.status["ready"] else "Initializing..."
    }


@app.post("/chat", response_model=ChatResponse)
def chat(query: ChatQueryCreate, db: Session = Depends(get_db)):
    if not ai_assistant.status["ready"]:
        raise HTTPException(status_code=503, detail="AI is still initializing. Please wait.")

    answer = ai_assistant.ask(query.question)

    # Save to database
    db_chat = ChatHistory(question=query.question, answer=answer)
    db.add(db_chat)
    db.commit()
    db.refresh(db_chat)

    return db_chat


@app.get("/chat-history", response_model=List[ChatHistoryResponse])
def get_chat_history(skip: int = 0, limit: int = 50, db: Session = Depends(get_db)):
    chats = db.query(ChatHistory).order_by(ChatHistory.timestamp.desc()).offset(skip).limit(limit).all()
    return chats


@app.post("/contacts", response_model=UserContactResponse)
def create_contact(contact: UserContactCreate, db: Session = Depends(get_db)):
    db_contact = UserContact(**contact.dict())
    db.add(db_contact)
    db.commit()
    db.refresh(db_contact)
    return db_contact


@app.get("/contacts", response_model=List[UserContactResponse])
def get_contacts(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    contacts = db.query(UserContact).order_by(UserContact.timestamp.desc()).offset(skip).limit(limit).all()
    return contacts


@app.get("/company-info")
def get_company_info():
    return ai_assistant.get_company_contact_info()