# -*- coding: utf-8 -*-
"""schemas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNgONYBZpRuwjaa4xwrqiTSevgU0pMwj
"""

from pydantic import BaseModel, EmailStr
from datetime import datetime
from typing import Optional


class ChatQueryBase(BaseModel):
    question: str


class ChatQueryCreate(ChatQueryBase):
    pass


class ChatResponse(BaseModel):
    question: str
    answer: str
    timestamp: datetime

    class Config:
        from_attributes = True


class UserContactBase(BaseModel):
    name: str
    email: EmailStr
    phone: str


class UserContactCreate(UserContactBase):
    pass


class UserContactResponse(UserContactBase):
    id: int
    timestamp: datetime

    class Config:
        from_attributes = True


class ChatHistoryResponse(BaseModel):
    id: int
    question: str
    answer: str
    timestamp: datetime

    class Config:
        from_attributes = True


class InitStatusResponse(BaseModel):
    ready: bool
    pages_scraped: int
    message: str